### ISSUE TITLE
How might I test a Microsoft Teams / Bot Framework bot built with Botkit with botkit-mock?

### ISSUE THREAD

**Issue by fbessez** [gratifyguy/botkit-mock#29]
Hey all,

I am building a bot for Microsoft environments via Botkit (since they now support the Bot Framework), but I am unsure of how to test properly. Do you mind providing me a very basic example? Thanks!

**Comment by ihorrusinko** [comment]
hey @fbessez would you could simple example of your code?

**Comment by fbessez** [comment]
Of course, just for a basic help message that returns a Rich Card / Adaptive Card
`controller.hears('help', 'message_received', MiscUtls.help`

`MiscUtils.help = (bot, message) => {
	const reply = {
		attachments: [
		{
			contentType: "application/vnd.microsoft.card.adaptive",
			content: 
				{
					type: "AdaptiveCard",
					body: [
					{
						type: 'TextBlock',
						text: 'Log Work',
						size: 'large',
						weight: 'bolder'
					},
					{
						type: 'TextBlock',
						text: 'You can log work on JIRA issues. Select an issue from the issue dropdown, enter the time spent on the issue, then write a short description of what you did.',
						size: 'normal',
						weight: 'normal',
						separation: 'none',
						wrap: true
					},
					{
						type: 'TextBlock',
						text: 'Get Timesheet',
						size: 'large',
						weight: 'bolder'
					},
					{
						type: 'TextBlock',
						text: 'You can retrieve a link to your Tempo timesheet and view its status and the total number of hours logged. Click the link to continue working on your Timesheet in JIRA.',
						size: 'normal',
						weight: 'normal',
						separation: 'none',
						wrap: true
					}
					]
				}
			}]
		}
	bot.reply(message, reply);
};`

Does that help? Thank you!

**Comment by amplicity** [comment]
Hey, yeah we'll take a look at this. I believe we can add an extender as
seen in our readme. I'll talk it over with ihor and we'll get back to you
ASAP.

**Comment by fbessez** [comment]
Sweet, thank you!

**Comment by ihorrusinko** [comment]
Your main entry point `app.js`
```javascript

var Botkit = require('botkit');
var controller = Botkit.botframeworkbot({
  debug: true
});

// Create the Botkit controller, which controls all instances of the bot.
var bot = controller.spawn({
  appId: process.env.app_id,
  appPassword: process.env.app_password
});


require('./indexController')(controller);
```
Logic of actions (indexController.js):
```javascript
var MiscUtls = {};

MiscUtls.help = (bot, message) => {
  const reply = {
    attachments: [{
      contentType: "application/vnd.microsoft.card.adaptive",
      content: {
        type: "AdaptiveCard",
        body: [{type: 'TextBlock', text: 'Log Work', size: 'large', weight: 'bolder'}, {
          type: 'TextBlock',
          text: 'You can log work!',
          size: 'normal',
          weight: 'normal',
          separation: 'none',
          wrap: true
        }, {type: 'TextBlock', text: 'Get your time', size: 'large', weight: 'bolder'}, {
          type: 'TextBlock',
          text: 'Time.',
          size: 'normal',
          weight: 'normal',
          separation: 'none',
          wrap: true
        }]
      }
    }]
  };
  bot.reply(message, reply);
};

module.exports = function (controller) {
  controller.hears('help', 'message_received', MiscUtls.help)
};
```
tests:
```javascript
'use strict';
const assert = require('assert');
const Botmock = require('botkit-mock');
const fileBeingTested = require("./indexController");

describe("controller tests", () => {
  afterEach(() => {
    //clean up botkit tick interval
    this.controller.shutdown()
  });
  
  beforeEach(() => {
    this.userInfo = {
      slackId: 'user123',
      channel: 'channel123',
    };
    
    this.controller = Botmock({
      debug: false,
    });
    
    this.bot = this.controller.spawn({});
    
    fileBeingTested(this.controller);
  });
  
  it('should return correct attachments object in message', () => {
    let sequence = [
      {
        //type: null, //if type null, default to direct_message
        user: this.userInfo.slackId, //user required for each direct message
        channel: this.userInfo.channel, // user channel required for direct message
        messages: [
          {
            text: 'help',
            isAssertion: true,
          }
        ]
      }
    ];
    
    return this.bot.usersInput(sequence).then((message) => {
      let testValue = {
        attachments: [{
          contentType: "application/vnd.microsoft.card.adaptive",
          content: {
            type: "AdaptiveCard",
            body: [{type: 'TextBlock', text: 'Log Work', size: 'large', weight: 'bolder'}, {
              type: 'TextBlock',
              text: 'You can log work!',
              size: 'normal',
              weight: 'normal',
              separation: 'none',
              wrap: true
            }, {type: 'TextBlock', text: 'Get your time', size: 'large', weight: 'bolder'}, {
              type: 'TextBlock',
              text: 'Time.',
              size: 'normal',
              weight: 'normal',
              separation: 'none',
              wrap: true
            }]
          }
        }]
      };
      return assert.deepEqual(message.attachments, testValue.attachments);
    })
  });
});

**Comment by fbessez** [comment]
Beautiful! I really appreciate all of the work you have put in! I will double check to see if this works upon returning to work :)

**Comment by fbessez** [comment]
Great! It works wonderfully! Do you mind also mapping out for me how I'd go about testing a conversation? So if user says 'What is my name?' then bot should respond 'fbessez, right?' and then I would say 'yes' or 'no'. How do I test that out? Do I add those messages to the sequence? and then add responses?

**Comment by ihorrusinko** [comment]
@fbessez checkout that example please
https://github.com/gratifyguy/botkit-mock/tree/master/examples/convo-bot
