### ISSUE TITLE
100ms is not enough for some responses

### ISSUE THREAD

**Issue by Naktibalda** [gratifyguy/botkit-mock#30]
I am using Watson Conversation in my bot and 100ms timeout (hardcoded [here](https://github.com/gratifyguy/botkit-mock/blob/ee7817318c1017bcded3b2c9b17d104e9ce577d1/lib/BotmockWorker.js#L96)) is not enough.
Manually editing the file to change timeout to 1000ms makes it work, but it makes all tests slower so it isn't a good solution.
Also I want to do some processing which takes multiple seconds before sending the response.

Would it be possible to handle messages with callback on reply instead of setting a timeout? That way quick responses would be processed quickly and slow responses would get more time without making everything slow.

**Comment by ihorrusinko** [comment]
@Naktibalda have you tried that?
```javascript
messages:[
{
  text: 'some reply',
  timeout: 1000,
},
{
  text: 'reply with typing',
  timeout: 500,
  isAssertion:true,
}]
```
 you may add timeout to some messages if need

**Comment by amplicity** [comment]
@ihorrusinko he's asking if there is a way to use callbacks instead of timeouts. 

I agree with him that this would be more optimal than using timeouts, since timeouts are arbitrary and can affect test suite speed in a linear fashion.

**Comment by amplicity** [comment]
@Naktibalda we're gonna pow-wow this locally and discuss / cycle back to this thread.

**Comment by Naktibalda** [comment]
Setting timeout property in the message does not help.
The test take longer, but fails in the same way:
`AssertionError: undefined == 'I heard a test'`

**Comment by ihorrusinko** [comment]
hey @Naktibalda 
we need you
1. to give an example of api you want
2. to give an example of your code

look forward to your answer

**Comment by Naktibalda** [comment]
I had another look at this code:
https://github.com/gratifyguy/botkit-mock/blob/ee7817318c1017bcded3b2c9b17d104e9ce577d1/lib/BotmockWorker.js#L83-L100

```js
var logic = function(){
    message.channel = message.channel || userMessage.channel;
    message.user = message.user || userMessage.user;
    message.type = (message.type || userMessage.type || 'direct_message');

    bot.receive(message);

    setTimeout(function(){
        if(message.isAssertion){
            cb({payload: {isAssertion: true, deep: message.deep, channel: message.channel}});
        }else{
            cb(null)
        }
    }, 100);
};

//add default timeout for async workflow
setTimeout(logic, message.timeout || 100)
```

It appears that `message.timeout` is a pause before calling `bot.receive` method,
and then the bot only gets 100ms (hardcoded amount) to respond.

I think that the `message.timeout` should be used after `bot.receive` and `default timeout` could be set to 0 to remove unnecessary pause, but keep things async.

**Comment by amplicity** [comment]
@Naktibalda thanks for this, we're taking a look at your PR.

**Comment by ihorrusinko** [comment]
@v1adko could you show your use case

**Comment by v1adko** [comment]
@ihorrusinko I've created [an example repo](https://github.com/v1adko/botkit-mock-bug/commits/master) with a failing test and a suggested patch (might help).
I also use a small custom wrapper on the library and `usersInput` method in particular just to give me extra freedom (assertion on reactions in my case). But I doubt it affects the library behavior.

There's a long running task (2 seconds in example), and it was failing the test (not waiting for the value and returning null). Basically `timeout` parameter on the message was not affecting how long it waits before asserting on the result.

Maybe I've misunderstood the meaning of the timeout parameter but in my head it's "give this call some time to do its thing and then assert on the result"...

Pathing lines [#105](https://github.com/gratifyguy/botkit-mock/blob/master/lib/BotmockWorker.js#L105) and [#109](https://github.com/gratifyguy/botkit-mock/blob/master/lib/BotmockWorker.js#L109) in `BotmockWorker.js` solved it for me - you can take a look at the [tests on CI](https://circleci.com/gh/v1adko/botkit-mock-bug).
Hope that helps.

**Comment by ihorrusinko** [comment]
@v1adko thank you for hard work with example and solution. i have a solution for you, i would name it workaround ;)
you send to bot single message (based on your repo): 
```javascript
 const response = await message.send('timeout', {
      full: true,
      timeout: 3000
 });
```
in botmock way it looks like:
```javascript
this.bot.usersInput([
	{
		user,
		channel,
		type,
		messages: [{
			text: 'timeout',
			isAssertion: true,
			timeout: 3000,
		}]
	}
])
```
i want to suggest simple way (add empty message with timeout at the end of sequence, it waits 3000 ms before return result )
```javascript
this.bot.usersInput([
	{
		user,
		channel,
		type,
		messages: [{
			text: 'timeout',
		}, {
			isAssertion: true,
			timeout: 3000,
		}]
	}
])
```

**Comment by v1adko** [comment]
Thanks. Yeah, it does look like a workaround because it doesn't truly mimic the user behavior (or does it)? Is my patch legitimate? I checked and it doesn't break any tests. Would you welcome a PR?

Because I think ultimately it's ought to be fixed or this kind of nuance specified in the documentation... Maybe a small section on "asserting the long-running commands".

**Comment by amplicity** [comment]
Hi Vlad, you can absolutely submit a PR to fix what you and Ihor are
discussing. Do you mind pushing a PR and we'll take a look asap?  Thanks
