### ISSUE TITLE
Indentation Issue in Test Example

### ISSUE THREAD

**Issue by TheJimFactor** [gratifyguy/botkit-mock#34]
In  https://github.com/gratifyguy/botkit-mock/blob/master/examples/convo-bot/indexController.js lines 2 and 3 and 33-43 should be indented one less.

**Comment by amplicity** [comment]
Briefly checked this out but was unfortunately unable to see what you're referring to. The indentations look correct to me on first glance. 

If you still believe they're off, please submit a PR and we'll take a look.
