### ISSUE TITLE
Support replyAndUpdate

### ISSUE THREAD

**Issue by ekristen** [gratifyguy/botkit-mock#36]
It would be great if this mock library could also support the `replyAndUpdate` function from botkit. 

Thanks for the library!

**Comment by amplicity** [comment]
@ekristen we'll add this functionality to projects (https://github.com/gratifyguy/botkit-mock/projects) and see if we can get someone to help us support `replyAndUpdate`. 

Feel free to submit a PR patching `replyAndUpdate` support if you write it first!

**Comment by ihorrusinko** [comment]
@ekristen already merged https://github.com/gratifyguy/botkit-mock/pull/35 + published to npm `0.1.3`

**Comment by amplicity** [comment]
thanks ihor!

**Comment by ekristen** [comment]
Thanks!
