### ISSUE TITLE
Test controller.api.* (eg. Facebook's messenger_profile) functions

### ISSUE THREAD

**Issue by natterstefan** [gratifyguy/botkit-mock#37]
Hi guys,

I have again a question. How can I test (no clue yet) features of the Facebook Bot, such as this one`controller.api.messenger_profile.get_messenger_code` (there are other `controller.api.*` features as well).

Based on the examples of you readme, I was not able to run a test like this:

```js
it('the bot\'s get_messenger_code should be a function', () => {
    this.controller.api.messenger_profile.get_messenger_code.should.be.a.Function();
  });
``` 

This is the skill (basically the example from the botkit repo):

```js
module.exports = function(controller) {

  // returns the bot's messenger code image
  controller.hears(['code'], 'message_received,facebook_postback', function(bot, message) {

    controller.api.messenger_profile.get_messenger_code(2000, function(err, url) {

      if (!err) {

        const image = {
          attachment: {
            type: 'image',
            payload: {
              url,
            },
          },
        };
        bot.replyWithTyping(message, image);
      }

    });

  });

};

```

**Comment by amplicity** [comment]
hey @natterstefan , we don't support that function (yet), but you could easily add it using `botExtender` (see *Advanced Usage* on readme).

Let me know if you're not able to figure it out, it should be added to the project so you don't need to use `botExtender`. Feel free to make a PR if you're able to patch it before us.

**Comment by natterstefan** [comment]
@amplicity thanks for the hint. I tried it, see:

```js
beforeEach((done) => {
    // mock data
    this.user = {
      id: 'user123',
      name: 'user',
      channel: 'channel',
    };

    // extend the bot w/ some extended features
    const botExtender = (parmBot) => {
      const bot = _.clone(parmBot);
      bot.api = {};
      bot.api.messenger_profile = (data) => {
        bot.reply(message, data.message);
      };
    };

    // mock fb bot
    this.controller = Botmock({
      debug: false,
      log: false,
    });
    this.bot = this.controller.spawn({ type: 'facebook', botExtender });
    skillController(this.controller);

    done();
  });
```

I still get the following error: _Uncaught TypeError: Cannot read property 'messenger_profile' of undefined_ (see the skill code above).

**Comment by ihorrusinko** [comment]
hey @natterstefan  please exclude `_.clone`, you should add new functionality to `bot` entity by reference.

**Comment by natterstefan** [comment]
@ihorrusinko good point. I had to disable the esLint for this line, that's why I added it. Still I am not sure if I added/used the botExtender the right way. As - for instance - the `get_messenger_code` is part of the `controller`, not the `bot` (see `controller.api.messenger_profile.get_messenger_code`).

**Comment by ihorrusinko** [comment]
@natterstefan sorry, was wrong.
`botExtender(bot, botkit, config)` has few additional params.
you need to add `.api. messenger_profile.get_messenger_code ` to `botkit` instance, `botkit` it's a controller. so it should works as you expected.

**Comment by natterstefan** [comment]
@ihorrusinko Aaaah, I should have seen that in your [Readme](https://github.com/gratifyguy/botkit-mock#advanced-usage) ^^. Looks like this one is working.
