### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by pauldariye** [gratifyguy/botkit-mock#39]
I keep getting `undefined` for `message.text`.

<img width="1176" alt="screen shot 2018-05-29 at 00 51 06" src="https://user-images.githubusercontent.com/3650761/40638648-6bfee5f6-62da-11e8-9ae3-d53e5d1cf93d.png">

This is my code:

```javascript
const assert = require('assert')
const botmock = require('botkit-mock')
const skill = require('../../server/skills/profile')

describe('[skill]: profile', function () {

  afterEach(function () {
    this.controller.shutdown()
  })

  beforeEach(function () {
    this.userInfo = {
      slackId: 'user123',
      channel: 'channel123'
    }

    this.controller = botmock({
      stats_optout: true,
      debug: false
    })

    this.bot = this.controller.spawn({
      type: 'slack'
    })

    skill(this.controller)
  })

  describe('hears profile', function () {
    beforeEach(function () {
      this.term = 'profile'
    })

    describe('as direct message', function () {
      beforeEach(function() {
        this.sequence = [
          {
            type: 'direct_message',
            user: this.userInfo.slackId,
            channel: this.userInfo.channel,
            messages: [
              {
                text: this.term,
                isAssertion: true
              }
            ]
          }
        ]
      })
      describe('with [1] trigger and [1] convos', function () {
        beforeEach(function () {
          this.bot.receive({ type: 'heard_trigger' })
          this.bot.receive({type: 'conversationStarted'})
        })

        it (`should return text: "Here's your preferences"`, function () {
          return this.bot.usersInput(this.sequence).then((message) => {
            console.log(this)
            return assert.equal(
              message.text.indexOf(`Here's your profile preferences`) > -1,
              true
            )
          })
        })
      })
    })
  })
})
```
Did I miss anything? I'm following the [botkit-starter-slack example](https://github.com/gratifyguy/botkit-mock/tree/master/examples/botkit-starter-slack)

**Comment by amplicity** [comment]
@pauldariye could you print `this.bot.detailed_answers` instead of `this` in your `console.log(this)`?

**Comment by pauldariye** [comment]
hey @amplicity, 

I'm getting this error: 
<img width="1293" alt="screen shot 2018-05-29 at 11 45 20 am" src="https://user-images.githubusercontent.com/3650761/40669858-ea8a42f2-6335-11e8-908c-ec9b9060c6ca.png">

**Comment by pauldariye** [comment]
hey @amplicity, I think the issue is that I am trying to make some api calls to enrich the data. To get the tests passing, I'll have to figure out a way to stub those.

**Comment by amplicity** [comment]
Apologies for the late reply.

Let us know if this works and I'll close this issue, @pauldariye

**Comment by pauldariye** [comment]
Thank you @ihorrusinko @amplicity, I'll give this a try tomorrow and let you know if it resolves the issue.

**Comment by pauldariye** [comment]
hey @amplicity, just checking on this. I'm looking to add `startPrivateConversation` in the slackBotWorker module to test it that will resolve the issue I'm having.

**Comment by ihorrusinko** [comment]
@pauldariye we've released version 0.1.8 with support for the function `createPrivateConversation`.

fyi here is example how to provide correct `im.open` response for this function 
https://github.com/gratifyguy/botkit-mock/blob/a19fa059916e3bbca2564ff12973a5eef8c2a695/tests/extendSlackBotMochaSpec.js#L57

**Comment by pauldariye** [comment]
Thank you @ihorrusinko !!! :fire:

**Comment by pauldariye** [comment]
@ihorrusinko I just upgraded to v`0.1.8` and I'm getting an error when I try using `bot.createPrivateConversation` (see below). However, it works just fine with either `bot.createConversattion` or **`bot.startPrivateConversation`**. 

Code snippet:
```javascript
const conversation = require('./conversation')
module.exports = (controller) => {
  controller.hears(
    ["check-in", "checkin"],
    "direct_message, direct_mention",
    (bot, message) => {
      bot.startPrivateConversation(message, (err, convo) => {
        if (!err) conversation(controller, bot, convo)
      })
    })
}
```

### Error message using `createPrivateConversation`
<img width="1440" alt="screenshot 2018-06-08 12 10 05" src="https://user-images.githubusercontent.com/3650761/41168930-5d5c135a-6b15-11e8-87ef-b3503f8e3496.png">

**Comment by amplicity** [comment]
@pauldariye we're checking this out.

**Comment by pauldariye** [comment]
Thank you @amplicity

**Comment by ihorrusinko** [comment]
@pauldariye see version `0.1.9`

example here

https://github.com/gratifyguy/botkit-mock/blob/f8b0586118dfade61140de085231630f12f442c5/tests/extendSlackBotMochaSpec.js#L101-L145

**Comment by amplicity** [comment]
@pauldariye let us know if this works and we'll close this out.

**Comment by pauldariye** [comment]
it works @amplicity @ihorrusinko !!!  Thanks a lot, guys. This lib has saved me a lot of work!!! Feel free to close this issue. 

I have one last question, how do I preload variables before a conversation I'm testing?

**Comment by amplicity** [comment]
Hmmm, I'm not exactly sure what you mean here. Could you show me an example of what you're trying to do?

**Comment by pauldariye** [comment]
Hey @amplicity, somehow didn't get to see this early. 

So  have a scripts that use the `beforeThread` hooks to pass in data to enrich the conversation. 

Like so:

```javascript

module.exports = (controller, bot, conversation) => {
  conversation.addMessage(
    {
      text: "You're email is *{{vars.user.email}}*.",
      action: "completed"
    }, 'default')
  )
/*
 * Before hooks
 */
conversation.beforeThread('default', async (convo, next) => {
    const { user: userId } = convo.context
    const [err, user] = await to(controller.storage.users.get(userId))
    ...
    convo.setVar('user', user)
    ...
})
}

**Comment by ihorrusinko** [comment]
@pauldariye i've tested this flow, i noticed you don't invoke `next()` in `beforeThread`.

btw i think your logic doesn't not visit `beforeThread`, you need invoke `convo.gotoThread('default')` before.

**Comment by pauldariye** [comment]
hey @ihorrusinko, good catch there. By default, all conversations start with the default thread. So once activated, a conversation will visit the `default` thread if one exists unless otherwise specified.

**Comment by ihorrusinko** [comment]
@pauldariye i tried your example, it does not work for me, `beforeThread` is  never invoked

**Comment by pauldariye** [comment]
That's really strange because I've been using it this way for some time. 

Here's an example from the [botkit doc](https://github.com/howdyai/botkit/tree/v0.6.9/docs):

```javascript
bot.createConversation(message, function(err, convo) {

    // create a path for when a user says YES
    convo.addMessage({
            text: 'You said yes! How wonderful.',
    },'yes_thread');

    // create a path for when a user says NO
    convo.addMessage({
        text: 'You said no, that is too bad.',
    },'no_thread');

    // create a path where neither option was matched
    // this message has an action field, which directs botkit to go back to the `default` thread after sending this message.
    convo.addMessage({
        text: 'Sorry I did not understand.',
        action: 'default',
    },'bad_response');

    // Create a yes/no question in the default thread...
    convo.addQuestion('Do you like cheese?', [
        {
            pattern: 'yes',
            callback: function(response, convo) {
                convo.gotoThread('yes_thread');
            },
        },
        {
            pattern: 'no',
            callback: function(response, convo) {
                convo.gotoThread('no_thread');
            },
        },
        {
            default: true,
            callback: function(response, convo) {
                convo.gotoThread('bad_response');
            },
        }
    ],{},'default');

    convo.activate();
});
```

Does this works for you?

**Comment by pauldariye** [comment]
Just confirmed @ihorrusinko and you're right. I needed to explicitly invoke `conversation.gotoThread('default')` after the `.activate()`
