### ISSUE TITLE
Does it work with SocketBot?

### ISSUE THREAD

**Issue by simonfranzen** [gratifyguy/botkit-mock#43]
No issue, just a question. Thanks!

**Comment by ihorrusinko** [comment]
hey @simonfranzen not, it does not.

**Comment by simonfranzen** [comment]
hey @ihorrusinko, we are using the SocketBot, but it is also possible to just test specific skills/conversation-controller with botkit-mock. 

So we are testing successfully our bot with botkit-mock, although the real application uses websockets.

thanks for the response
