### ISSUE TITLE
Where is "this" coming from in the examples

### ISSUE THREAD

**Issue by simonfranzen** [gratifyguy/botkit-mock#44]
I tried to setup the botkit-mock and I am a bit confused where "this" comes from

```
describe("controller tests",()=>{
    beforeEach(()=>{
        this.controller = Botmock({}); // is unndefined

```

I tried it also to just define controller and bot as variables in the test, but my testbot is still not responding.

**Comment by simonfranzen** [comment]
Found out that my bot was not responding, because it sent "direct_message" and I was only listening to "message_received".

Anyway: "this" is undefined and I got it working with defining `var controller, bot;` in my spec and use these variables instead of `this.controller` and `this.bot`.

**Comment by ihorrusinko** [comment]
hey @simonfranzen, `this.controller` you could use it in pair with arrow function where you bind `this` to function. you could use `var controller, bot` it works too.

does `message_received`  work as expected?

**Comment by simonfranzen** [comment]
yes everything works as expected. Just had a few problem to start with your framework :)
