### ISSUE TITLE
Relax deps permit use of 4.x

### ISSUE THREAD

**Issue by lpil** [gratifyguy/botkit-mock#46]
Currently the package.json specifies the 0.x line, which means if the application uses 4.x then two versions of botkit are installed. It would be great to permit use of the 4.x version to avoid this duplication and to shrink the size of node_modules

**Comment by amplicity** [comment]
Unfortunately we haven't had time to upgrade botkit-mock to 4.x (yet). We don't fully support it at this time and therefore have not changed the package.json line. 

If you, or anybody else, would like to help migrate support to 4.x, please submit a PR

**Comment by lpil** [comment]
Thanks
