### ISSUE TITLE
v4 is a breaking change. 

### ISSUE THREAD

**Issue by roeintense** [gratifyguy/botkit-mock#47]
Hi guys. 

Manually updating the botkit dependency to the most recent version squishes `botkit-mock` and it rejects running tests. And of course, testing my bot's skills with the old version defeats the purpose. 

How can I help get this going for the new version of Botkit? You guys already working on it?

**Comment by amplicity** [comment]
Hey roeintense, at this time we don't support 4.x. We are working on an upgrade (slowly) but do not have an ETA. If you or anyone else would like to help migrate support and submit a PR, we'll gladly review. 

@ihorrusinko tagging you for any update on timeline / specific tasks people could take to PR 4.x functionality.

**Comment by ihorrusinko** [comment]
Hi @roeintense 
[here](https://github.com/gratifyguy/botkit-mock/pull/49) is some draft work of update to botkit 4.0
we need help with an advance integration for facebook or any other providers.
we have some breaking changes you can see basic new examples how to use botmock in readme.md

**Comment by Benedict** [comment]
Does that draft work play nicely with Botkit 4.5? I can't seem to get it to work. I keep getting the following error? Am I doing something wrong?

```
TypeError: BotMock is not a constructor
```

**Comment by Benedict** [comment]
Turns out the package.json wasn't referencing index.js so it couldn't find any of the modules. I've created a new pull request - #50

**Comment by ihorrusinko** [comment]
thanks @Benedict PR approved

**Comment by amplicity** [comment]
Master has been updated to support v4.0
