### ISSUE TITLE
Having trouble testing predefined botkit dialogs

### ISSUE THREAD

**Issue by yaron-idan** [gratifyguy/botkit-mock#52]
I'm trying to create test cases for a predefined dialog I've created with botkit.
The dialog creation code, in botkit's main file (`bot.js`) looks a bit like this - 
```
function createServiceDialog() {
    const MY_DIALOG_ID = 'my-dialog-name-constant';
    let convo = new BotkitConversation(MY_DIALOG_ID, controller);

    convo.say('Howdy!');

    ... // I've omitted most of the dialog for brevity's sake
}

controller.addDialog(createServiceDialog());
```

I later use this dialog like so - 
```
const { SlackDialog } = require('botbuilder-adapter-slack');
const { BotkitConversation } = require('botkit');
const MY_DIALOG_ID = 'my-dialog-name-constant';

module.exports = function(controller) {
    controller.hears('create_service', 'message', async(bot, message) => {
        await bot.startConversationInThread(message.channel, message.user, message.incoming_message.channelData.ts);
        await bot.beginDialog(MY_DIALOG_ID);
    });
}
```

If I try testing this file with hard coded messages, the tests pass just fine.
When I try to use this predefined dialog, I'm getting the following error - 
`(node:62437) UnhandledPromiseRejectionWarning: Error: DialogContext.beginDialog(): A dialog with an id of 'my-dialog-name-constant:botkit-wrapper' wasn't found.`

I've tried porting the dialog definition into the file being tested, but that didn't work nor felt like the right approach.
How should I go about implementing such a test case?

Oh, I almost forgot, here's the test suite I'm trying to execute - 
```
'use strict';
const assert = require('assert');
const {BotMock, SlackApiMock} = require('botkit-mock');
const {SlackAdapter, SlackMessageTypeMiddleware, SlackEventMiddleware} = require('botbuilder-adapter-slack');
const fileBeingTested = require('../features/create_service');

async function setTimeoutAsync(timeout = 100) {
    return new Promise((r) => setTimeout(r, timeout));
}

describe('create_service file slack-feature', () => {
    const initController = () => {
        const adapter = new SlackAdapter({
            clientSigningSecret: "some secret",
            botToken: "some token",
            debug: true,
        });
        adapter.use(new SlackEventMiddleware());
        adapter.use(new SlackMessageTypeMiddleware());

        this.controller = new BotMock({
            adapter: adapter,
        });

        SlackApiMock.bindMockApi(this.controller);

        fileBeingTested(this.controller);
    };

    beforeEach(() => {
        this.userInfo = {
            slackId: 'user123',
            channel: 'channel123',
        };
    });

    describe('create_service', () => {
        beforeEach(() => {
            initController();
        });
        it(`should reply in a correct sequence through message`, async () => {
            const reply = await this.controller.usersInput([
                {
                    type: 'message',
                    user: this.userInfo.slackId, //user required for each direct message
                    channel: this.userInfo.channel, // user channel required for direct message
                    messages: [
                        {
                            text: 'create_service',
                            isAssertion: true,
                        }
                    ]
                }
            ]);

            assert.strictEqual(this.controller.detailed_answers[this.userInfo.channel][0].text, `Howdy!`);
        });
    });
});
```

Thanks!

**Comment by ihorrusinko** [comment]
hey @yaron-idan,
did you test that dialog online with connected slack bot?

**Comment by yaron-idan** [comment]
Hey @ihorrusinko,
Yep, the dialog behaves as expected when I test it online.

**Comment by ihorrusinko** [comment]
got it, if you do not mind, please provide whole example of your code so i
can test it on my side.
thanks!

**Comment by yaron-idan** [comment]
Sure, I've created a gist with all of the required files, you can just paste them over the botkit boilerplate generated by yeoman.
The files starting with `create...` should be in the `features` folder and the files starting with `test...` should be in the tests folder.

**Comment by ihorrusinko** [comment]
hey @yaron-idan,
i've checked you gist, thanks - great work!
i found that you include dialog as part of your config file `bot.js`, so when you try to test single file you pass `controller` as dependency without dialog itself.

take a look [here](https://github.com/gratifyguy/botkit-mock/pull/53) i've provided super simple example how to make your tests working

**Comment by yaron-idan** [comment]
Whoa! This is really great. I was thinking there should probably be a way to load the controller as it's configured in `bot.js`, because my understanding of the [botkit docs](https://botkit.ai/docs/v4/conversations.html) led me to believe that's where I should be configuring my dialogs.
However, this can totally in the meantime and allow me to create test cases for the dialog I'm currently building, thanks alot!
