### ISSUE TITLE
Configurable baseUrl for use with yakbak

### ISSUE THREAD

**Issue by roeintense** [gratifyguy/botkit-mock#55]
Hi folks, 

I'd like to be able to configure the baseUrl of the underlying Axios adapter (using axios-mock-adapter) so that it hits a local endpoint spun up to use yakbak, a VCR technology so I can stub out API requests. Is that possible? I'm looking through source and I'm not seeing anywhere without monkey patching the source. Thanks.

**Comment by ihorrusinko** [comment]
Hey @roeintense,
I think you have access to axios after binding api mock
https://github.com/gratifyguy/botkit-mock/blob/5ab04f4fb23afce4306afd97889741ed173fa50e/lib/slack/ApiMock.js#L53-L57

or do you want specific interface to do this?

**Comment by amplicity** [comment]
@roeintense Did this end up working for you?
